spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 4
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationInMs: 604800000
main_server:
  base_URI: ${MAIN_SERVER_BASE_URI}
  login_username: ${MAIN_LOGIN_USERNAME}
  login_password: ${MAIN_LOGIN_PASSWORD}
  office_id: ${OFFICE_ID}
  business_id: ${BUSINESS_ID}
cron:
  main_fetch: ${MAIN_SYNC_CRON_TIME}
